language: cpp

env:
 - ARCH=32
 - ARCH=64

# Install prerequisites (and cache the packages)
# Note that OpenSSL should already be installed in the CI environment, but is
# included here anyway - Just In Case!(tm)
cache: apt
before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository -y ppa:wxformbuilder/wxwidgets
 - sudo apt-get update
 - sudo apt-get install boost1.55 libwxbase3.0-dev libwxgtk-media3.0-dev libwxgtk3.0-dev zlib yaml-cpp libloadorder openssl libgit2

# Build commands per docs/BUILD.MinGW.md
script:
 - mkdir build && cd build
 - cmake .. -DPROJECT_LIBS_DIR=".." -DPROJECT_ARCH=$ARCH -DPROJECT_LINK=STATIC -DCMAKE_TOOLCHAIN_FILE="mingw-toolchain.cmake"
 - make
